version: '3.7'

services:
  db:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  cache:
    image: redis:5-alpine
    ports:
      - 6378:6379

  job:
    image: redis:5-alpine
    ports:
      - 6379:6379

  worker:
    build: .
    command: bundle exec sidekiq
    environment:
      - REDIS_WORKER_URL=redis://job:6379/0
      - SIDEKIQ_THREADS=15
    depends_on:
      - job

  web:
    build: .
    command: bundle exec rails server -p 5000 -b 0.0.0.0
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=15
      - DATABASE_PRODUCTION_URL=postgres://postgre:changeme@db:5432/todo_production
      - DATABASE_DEVELOPMENT_URL=postgres://postgre:changeme@db:5432/todo_development
      - DATABASE_TEST_URL=postgres://postgre:changeme@db:5432/todo_test
      - REDIS_CACHE_URL=redis://cache:6379/0
      - REDIS_WORKER_URL=redis://job:6379/0
    depends_on:
      - db
      - cache
      - worker
      - job
